const ACTION_PREFIX = 'app/'

export const TOGGLE_DRAWER = `${ACTION_PREFIX}TOGGLE_DRAWER`
export const SET_PAGE_OPTIONS = `${ACTION_PREFIX}SET_PAGE_OPTIONS`
export const SET_SELECTED_ROBOT = `${ACTION_PREFIX}SET_SELECTED_ROBOT`

export const FETCH_ROBOTS = `${ACTION_PREFIX}FETCH_ROBOTS`
export const FETCH_ROBOTS_SUCCESS = `${FETCH_ROBOTS}_SUCCESS`
export const FETCH_ROBOTS_ERROR = `${FETCH_ROBOTS}_ERROR`

export const ROBOT_UPDATED = `${ACTION_PREFIX}ROBOT_UPDATED`

export const ADD_SNACKBAR_MESSAGE = `${ACTION_PREFIX}ADD_SNACKBAR_MESSAGE`
export const REMOVE_SNACKBAR_MESSAGE = `${ACTION_PREFIX}REMOVE_SNACKBAR_MESSAGE`

export const DRAWER_WIDTH = 240
