export const PERMISSIONS = {
    ROBOT: {
        GET_DEVICES: 'ROBOT_GET_DEVICES',
        CHANGE_MANUAL_CONTROL: 'ROBOT_CHANGE_MANUAL_CONTROL',
        RUN_LIMIT_FINDING: 'ROBOT_RUN_LIMIT_FINDING',
    },
}
